### ISSUE TITLE
EditTable and the DataTables Plugin -> Table Headers

### ISSUE THREAD

**Issue by LP2465** [cosmocode/edittable#104]
IMHO, the EditTable plugin is mishandling table headings, which results in DataTables not understanding the table correctly.

Original table using the DataTables Plugin:
<datatables fixed-header='{ "header": true, "headerOffset": 50 }' paging="true">
^    ^  This is the main title line                              ^^^
^    ^ Subtitle #1                   ^ Subtitle #2  ^ Subtitle #3  ^
^ 1  | Row A2                        | Row B2       | Row C2       |
^ 2  | Row A3                        | Row B3       | Row C3       |
</datatables>

After editing the table with EditTable:
<datatables fixed-header='{ "header": true, "headerOffset": 50 }' paging="true">
^    ^  This is the main title line                              |||
^    ^ Subtitle #1                   ^ Subtitle #2  ^ Subtitle #3  ^
^ 1  | Row A2                        | Row B2       | Row C2       |
^ 2  | Row A3                        | Row B3       | Row C3       |
^    | new                           |              |              |
</datatables>

**Comment by splitbrain** [comment]
The final closing element can be a ``^`` or a ``|`` it does not influence the output and DokuWiki accepts both. So if another plugin fails to parse a valid DokuWiki table I'd argue that other plugin needs to be fixed.
