### ISSUE TITLE
Edittable and media manager not always working - images are not inserted

### ISSUE THREAD

**Issue by ruud12** [cosmocode/edittable#153]
Regularly images won't insert into a table edited by edittable. No js errors are visible in the error log besided an TypeError (JSINFO.fastwiki is undefined). I already tried to disable fastwiki, but no difference unfortunately.

To clarify: when editing a page the normal way, images/files insert just fine. Only when the edittable editor is used, images/files won't insert, the selected cells stays blank. Is there anything i'm missing? I have tried firefox and internet explorer, the images/files are not inserted in either of them.

**Comment by micgro42** [comment]
You need to actually click into a cell until the cursor appears before using toolbar icons. Unfortunately, there doesn't seem to be a way around that.
