### ISSUE TITLE
Can't save edited tables after switching to php-7.3

### ISSUE THREAD

**Issue by pornmailbox** [cosmocode/edittable#165]
[error] 1160#1160: *138 FastCGI sent in stderr: "PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/localhost/htdocs/dokuwiki/lib/plugins/edittable/action/editor.php on line 129PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/localhost/htdocs/dokuwiki/lib/plugins/edittable/action/editor.php on line 130PHP message: PHP Warning:  Illegal string offset 'align' in /var/www/localhost/htdocs/dokuwiki/lib/plugins/edittable/action/editor.php on line 140PHP message: PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in /var/www/localhost/htdocs/dokuwiki/lib/plugins/edittable/action/editor.php:147

**Comment by janlinde** [comment]
Same here, PHP php7-7.2.11. Reverting commit splitbrain/dokuwiki@2145bd4c56435f829a19aad843172f8ddffbc69b makes the problem go away.

**Comment by splitbrain** [comment]
probably fixed by https://github.com/splitbrain/dokuwiki/pull/2686
