### ISSUE TITLE
less code not translateable?

### ISSUE THREAD

**Issue by LarsGit223** [cosmocode/edittable#179]
I noticed that some portions of ```edittable/lib/handsontable.less``` do not seem to be translated into valid CSS code. The CSS code of a DokuWiki page e.g. includes the following if the edittable plugin is installed and enabled:
```
@keyframes wtFadeInFromNone{0%{display:none;opacity:0;}1%{display:block;opacity:0;}100%{display:block;opacity:1;}}
@-webkit-keyframes wtFadeInFromNone{0%{display:none;opacity:0;}1%{display:block;opacity:0;}100%{display:block;opacity:1;}}
```

P.S.: This breaks CSS loading/interpreting in the ODT plugin as my parser is not expecting less code in CSS files. It would be nice if this could be fixed :grin: 

At least this looks like less code to me. Please correct me if I am wrong or have overseen something.

**Comment by splitbrain** [comment]
This is actually not less but valid CSS (it's used to define CSS animations) You may want to simply strip or ignore these.

**Comment by LarsGit223** [comment]
Ahh...thanks, did not know that. I assumed it was less code because of the nested ```{...}```. But I found a description at https://www.w3schools.com/css/css3_animations.asp.

> You may want to simply strip or ignore these.

Well, as it's valid CSS I consider this a bug in my CSS parser. So I will have to address it. Sorry for the false ticket.

**Comment by LarsGit223** [comment]
A little update: the issue in the ODT plugin is fixed, see https://github.com/LarsGit223/dokuwiki-plugin-odt/issues/245.
