### ISSUE TITLE
edittable no longer working as expected?

### ISSUE THREAD

**Issue by DirkED** [cosmocode/edittable#187]
I'm using the acual plugin with the last version of DokuWiki but editing the tables seems not
to work as expected. The menu looks strange and misplaced, a right-click menu is on the lower
left edge outside the editing screen.

I tested it with firefox and chromium on debian linux. I'm doing something wrong?

![Screenshot-edittable](https://user-images.githubusercontent.com/52004729/79774288-e7df5c80-8332-11ea-88cd-7fa51179727f.png)

**Comment by splitbrain** [comment]
It's working fine for me. Without any additional info, it's hard to know what's going wrong.

**Comment by DirkED** [comment]
Ok, what would be additional infos? It's the same with firefox and chromium. I did not find any log entries or where should I look for them?

**Comment by DirkED** [comment]
Strange, now it works. You can now ignore this issue.
