### ISSUE TITLE
not compatible with 2020-07-29 "Hogfather" 

### ISSUE THREAD

**Issue by f31n** [cosmocode/edittable#192]
Edit of tables does have only blank pages with new version!

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'Doku_Parser_Mode_externallink' not found in /www/lib/plugins/edittable/renderer/inverse.php:422
Stack trace:
#0 /www/lib/plugins/edittable/action/editor.php(74): renderer_plugin_edittable_inverse->externallink('http://something...', NULL)
#1 /www/inc/Extension/EventHandler.php(81): action_plugin_edittable_editor->editform(Object(dokuwiki\\Extension\\Event), NULL)
#2 /www/inc/Extension/Event.php(72): dokuwiki\\Extension\\EventHandler->process_event(Object(dokuwiki\\Extension\\Event), 'BEFORE')
#3 /www/inc/Extension/Event.php(128): dokuwiki\\Extension\\Event->advise_before(true)
#4 /www/inc/Extension/Event.php(195): dokuwiki\\Extension\\Event->trigger('html_edit_form', true)
#5 /www/inc/html.php(1877): dokuwiki\\Extension\\Event::createAndTrigger('HTML_EDIT_FORMS...', Array, 'html_edit_form', t...', referer: https://example.com/doku.php?id=something:something:something`

**Comment by loganmarchione** [comment]
This appears to be the same as #190
