### ISSUE TITLE
Feature request: Simple total row

### ISSUE THREAD

**Issue by chrisjrob** [cosmocode/edittable#206]
I wonder whether a simple total row would be an option?

I'm thinking very basic formulas like =SUM (or just "=", or just the sigma summation symbol "∑"), to total all the cells in that column, and styling to indicate that the row is a total. A total column might be useful as well.

It could be much more complicated, with other mathematical functions, and using A1 or R1C1 cell referencing, but for such simple tables within a Wiki, I think that would be overkill, and presumably a lot more work.

Thank you.

**Comment by splitbrain** [comment]
This is an editor. It doesn't make sense that it would calculate anything. AFAIK there's a tablemath plugin you could use.
