### ISSUE TITLE
Editing UI rendering broken

### ISSUE THREAD

**Issue by forrest-lucas** [cosmocode/edittable#209]
I have release 2020-07-29 "Hogfather" installed on a Synology NAS; I'm having this issue where edittable breaks the UI after clicking the edit button. While I have the typography plugin (which I think conflicts), I have uninstalled it to no avail. 

I have a sneaking suspicion that the [material template ](https://www.dokuwiki.org/template:material) is causing this inflated UI.

I've also tried removing the wrap plugins, as well as the columns plugin.

![issue](https://user-images.githubusercontent.com/89580944/130948553-0d48a3f6-f4f8-41df-85de-c920db759a70.png) 
![plugins](https://user-images.githubusercontent.com/89580944/130948927-f73a945b-fd85-4f85-8672-d5919fe591c3.png)

**Comment by djonez** [comment]
We have same like issue on the newest version of Dokuwiki - Igor. Our old installation on 2020-07-29 "Hogfather" works perfectly and we'd love it to work on our new installation.  

Please check out and update the plugin. Thanks in advance.

**Comment by splitbrain** [comment]
The plugin works fine for me with Igor. If there's incompatibilities with templates either raise a bug there or provide a pull request to fix the issue (as long as compatibility is kept with the default template).
