### ISSUE TITLE
Default headers unclear

### ISSUE THREAD

**Issue by EdwinKM** [cosmocode/edittable#212]
I was puzzled by the editor after installing the plugin. I pressed the icon to create a new table. It opened the editor and was presented with the "1,2 and A,B" table.

So my first action is to change the headers to my liking. So i wanted to change "A" to my column title. But i can not modify this.
It seems the row below actually is the header. This not really clear for end users. To make things worse. While typing the font is not bold (to indicate that it is a header). Only after the <enter> the editor makes the font bold.

**Comment by splitbrain** [comment]
Sorry, the labeling of columns and rows this way is standard in any spreadsheet tool. It also the default behaviour of the used library so we won't change it.

Please also not that this is not a WYSIWYG editor.
