### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ajreaper** [cosmocode/edittable#215]
Updated the plugin on Greebo and was given an error 500 on entire wiki. Removing the plugin solves the problem. I tried the following:
* Changing the template
* Disabling all other plugins
* Clearing cache (not server-side)
* Deleting .htaccess on root and directory
* Plugins root does have the action file; removal of file also causes 500

No issue with previous version, even with action file.

Please advise. Thank you.

**Comment by heiko77** [comment]
I have the similar problem on Release 2018-04-22b "Greebo".

Thx

**Comment by Tazzzilo** [comment]
Same problem on Release 2017-02-19e "Frusterick Manners".

**Comment by bomhard** [comment]
Same here, edittable breaks Greebo on Debian 11 Bookworm (stable).

**Comment by splitbrain** [comment]
Sorry, the plugin is only compatible with the current stable release.
