### ISSUE TITLE
Request for new label / documentation on the conflict  EditTable/Bootswrapper

### ISSUE THREAD

**Issue by Nif9** [cosmocode/edittable#219]
Hi, 

I'm using edittable and bootstrap knowing there is a conflict. However, in my usage I don't get any immediate issue, I'm wondering why is there a conflict.
But sometimes (long time after forgetting this conflict issue), I get issues with my dokuwiki and I use a lot of time trying to find where it comes (from the conflict or not?).

Is it possible to have a label to identify issues leading to have make the plugin in conflict with another? This way, we know what not to use...

**Comment by splitbrain** [comment]
I'm not using the bootstrap template. Documentation is on an editable wiki for a reason. Users are encouraged to edit the pages when they can add useful info. If you know under which circumstances the plugin has problems with the template, feel free to add an appropriate section to the plugin page.
