### ISSUE TITLE
Internal Link Button

### ISSUE THREAD

**Issue by Braintelligence** [cosmocode/edittable#32]
Hi :).
The internal link button doesn't seem to work as it parses nothing at all when using it. I'm running Blinky with standard editor.

**Comment by konus1** [comment]
I can confirm this bug. After clicking on the link, nothing happens. 
I get the error:
"Fehler: NS_ERROR_FAILURE: 
Quelldatei: http://dokuwiki/lib/exe/js.php?tseed=0e4f6c54f1b599ca3a0174b42d425194
Zeile: 23"
With firefox 36.0 and 2014-09-29c "Hrun"

**Comment by micgro42** [comment]
The Bug still exists with the current edittable and dokuwiki master. The error in the console links to: https://github.com/splitbrain/dokuwiki/blob/7e487fcf7005d1e1465ef6acb332cc1009676413/lib/scripts/textselection.js#L132

**Comment by jenscooper** [comment]
Hello,

is this Bug going to be fixed?
We are using the plugin and it would be very nice, if we could use ist together with the internal link button.

Maybe someone knows a workaround and can share it with us?

Thank You! ;)

**Comment by lisps** [comment]
as a workaround you can change the line 17382 in `handsontable.full.js` from

```
if (that.settings.outsideClickDeselects) {
      instance.deselectCell();
    } else {
      instance.destroyEditor();
    }
```

to 
```
if (that.settings.outsideClickDeselects) {
      instance.deselectCell();
    } else {
    	if(!jQuery('#link__wiz').is(':visible')) {
    		instance.destroyEditor();
    	}
    }
```

the problem is that the edittable text field closes before the link wizard can insert the text.
I havn't found how to prevent it, so I fixed it with this workaround.
