### ISSUE TITLE
No edit button under the table and "insert a new table" is not working

### ISSUE THREAD

**Issue by mubed** [cosmocode/edittable#47]
I think there is a conflict with another plugin, because I see neither an edit button under the table nor I can add any new table using the "insert a new table" button in the editor, it shows a link to "Media Files" instead!

Tested with "Angua" and "Binky"

**Comment by mubed** [comment]
I got the latest versions of all the plugins, templates (monobook 2014-02-09), Dokuwiki (2014-09-29 "Hrun") and the latest version of EditTable (2014-06-18), But there are still problems with the context menu (other stuff work fine in Chrome but not in IE 11):

The context menu do apears, but **under** the whole page layout (see image)!
![dokuwiki_edittable_bug](https://cloud.githubusercontent.com/assets/694738/5759998/05add298-9cd2-11e4-813e-3f704e891eee.png)

**Comment by thewarden** [comment]
This is an issue with the template Monobook. However the same author created a new template called Vector and works perfectly with edittable.

**Comment by mubed** [comment]
You are right. It works fine under "vector", but only in Chrome and Firefox, not in IE 11 (11.0.9600.17358)
