### ISSUE TITLE
bug & feature request - multiline cells

### ISSUE THREAD

**Issue by ReHierl** [cosmocode/edittable#58]
First off: Thanks for this plugin, it makes life a lot easier.

Many programs take the Enter key as a request to start a new paragraph. If you press the Control/Alt key in addition to pressing the Enter key, most programs take this as a request to start a new line within the same paragraph.

EditTable's Textbox, that pops up when you press the Enter key on a selected cell, does accept both key combinations. Control/Alt+Enter does append a new line at the end of the cell's contents and moves the cursor to that position.

**Bug**: At that point you should **not save** the page, as this will mess up the table. It will be split into multiple tables because these line-breaks won't be "escaped" by EditTable.

If you allow embedded HTML within DokuWiki (Admin / Configuration settings / Editing / Allow embedded HTML), you could enter something like "prefix &lt;html&gt; &lt;br/&gt; &lt;/html&gt; suffix" which will be displayed as expected; "&lt;html&gt; prefix &lt;br/&gt; suffix &lt;/html&gt;" has the same effect. The only drawback is that, due to the additional and unnecessary visible "content", both versions are a bit difficult to edit within a small table.

**Feature**: I think it should be possible to change the implementation such that the inner line-breaks of EditTable are automatically converted into escaped line breaks and automatically converted back if the table's contents are about to be changed via the plugin. At least this could be one way to do it - there might be another and even better way.

**Hint**: EditTable's Textbox does not allow to use the up/down arrow keys to move the cursor to a different line within that cell. The left/right arrow keys on the other hand can be used to "navigate" within the multi-line text, If the cursor is not at the beginning/end of the cell's contents.

Maybe required to verify this? I do use - Windows 7 - Firefox 30 - DokuWiki (version) 20140505a a.k.a Ponder Stibbons - EditTable (last updated on) 2014-06-18

**Comment by micgro42** [comment]
#54 has been merged, so this issue should now be fixed.
