### ISSUE TITLE
Conflict with const Plugin

### ISSUE THREAD

**Issue by mko24** [cosmocode/edittable#64]
If I have more than one table on a wiki page and use variables of the const plugin within the table cells, editing of the tables with edittable is not longer possible. It looks like an offset problem. Normal section editing is possible.

Sample wiki page:
```
====== Test ======

<const>
DIR=\\SERVER\SHARE\FOLDER\SUBFOLDER
</const>

===== Test1 =====

^ APP  ^ PATH  ^ NOTES  ^
| App 123  | [[%%DIR%%\123]] | Test|
| App 456  | [[%%DIR%%\456]] | Test|

===== Test2 =====

|  ^ APP  ^ PATH  ^ NOTES  ^
| App abc  | [[%%DIR%%\abc]] | Test|
| App def  | [[%%DIR%%\def]] | Test|
```

**Comment by lisps** [comment]
this can be closed as it is fixed in const-plugin
