### ISSUE TITLE
EditTable plugin seems not to work at all in my setup

### ISSUE THREAD

**Issue by emilidza** [cosmocode/edittable#69]
Hi, 
I do not see any of the edit button available for the table. New table button also acts very strange; does not allow any modification it  inserts 2 column 2 row table only. I checked and plugin is lib/plugin. I have the newest version of dokuwiki Hrun and I also tried uninstaling and reinstalling the plugin via extension manager. 
![image](https://cloud.githubusercontent.com/assets/10189063/5429577/ed0656d4-83a4-11e4-8e4b-8ad7fd61ecb4.png)
If you experienced similar problems and do know the fix, could you please post it. Thanks.

**Comment by splitbrain** [comment]
are you getting any errors in the javascript console? is the plugin installed to the correct folder?

**Comment by Tynstar** [comment]
Hi, 
with my wiki this plugin also doesn't work. I just downloaded the current dokuwiki hrun and the current version of edittable (and copied it into the plugin folder). No buttons are shown anymore.

In my running system (upgraded from an older version to hrun) and some plugins like ckedit,... the buttons including the edittable button are shown but editing by using edittable first deletes the table and if i try it a second time, it destroys the hole page!

**Comment by splitbrain** [comment]
again. error messages in the console please.

**Comment by Tynstar** [comment]
Sorry, I forgot to mention, that the console doesn't say anything!

**Comment by splitbrain** [comment]
> No buttons are shown anymore.

Then your JavaScript is broken and there should definitively be some kind of error in the console.

> and some plugins like ckedit,... the buttons including the edittable button are shown

This plugin does not work with ckedit

**Comment by Tynstar** [comment]
There are two different systems with different problems.
I use a bare hrun-version + edittable (no other plugins are installed!). And no buttons are shown. And no javascript errors are reported.
The other system with ckedit has the problem, that text will be deleted. When this system has been based on binky, edittable worked fine together with ckedit. I could use dwedit + edittable or ckedit by switching the mode.

Is there any other usable WYSIWYG-editor for dokuwiki? CKG is not really good, but when not using html, you can work with it.

**Comment by splitbrain** [comment]
Can you explain what "no buttons are shown" means? Are just the table edit buttons missing or are no buttons shown in the toolbar?

**Comment by Tynstar** [comment]
Please see enclosed screenshot.

![edittable_no_buttons](https://cloud.githubusercontent.com/assets/4678533/6351375/508dc006-bc3b-11e4-91e4-f523513ca90e.PNG)

**Comment by splitbrain** [comment]
Okay. That's definitively a matter of non working JavaScript. Can you follow the steps here: https://www.dokuwiki.org/faq:toolbar and report back?

**Comment by fprigent** [comment]
Same problem for me.. But only on a dokuwiki on a centos 7 (RHEL 7), on a dokuwiki on a centos 6, all is OK.

same browser, same dokuwiki version some plugins are different, but not so much :
  - odt
  - keyboard
  - encryptedpassword

On the "bugged" dokuwiki, there is no incompatible plugins (I have remove previous "sortablejs").

I have even downgrade "edittable" to have exactly the same version...

the console say nothing....

**Comment by fprigent** [comment]
The problem disappeared with "dokuwiki" default template

**Comment by dmarcelino** [comment]
What fixed it for me was disabling CSS and JS compression (as mentioned in https://www.dokuwiki.org/faq:toolbar). Thanks!

**Comment by fprigent** [comment]
Le 20/10/2015 19:35, Dário a écrit :
>
> What fixed it for me was disabling CSS and JS compression (as 
> mentioned in https://www.dokuwiki.org/faq:toolbar). Thanks!
>

     Fine.

     Thank you.

**Comment by stvoigt** [comment]
Ich kehre zur�ck am 26.10.2015.

Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten. Herzlichen Dank
f�r ihr Verst�ndnis.

I will answer your message after returning.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[edittable] EditTable plugin seems not to work at all in my setup (#69)"
gesendet am 21.10.2015 15:31:34.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend
diese Person abwesend ist.

**Comment by Petikoch** [comment]
I had the same issue... I upgraded from "Weatherwax" to "Detritus". 

Disabling CSS and JS compression in the configuration solved the issue for me. Thanks to @dmarcelino for sharing this.
