### ISSUE TITLE
no mouse support in 2015-08-18

### ISSUE THREAD

**Issue by LMS235** [cosmocode/edittable#83]
after upgrade to 2015-08-18 on 2015-08-10a "Detritus" i cannot select rows or cells with the mouse
only cursor keys are working

error in IE10 and FF40

**Comment by LMS235** [comment]
error also in chrome

**Comment by micgro42** [comment]
This appears to be another conflict with the indexmenu plugin

**Comment by micgro42** [comment]
This should now be fixed with the newest version of indexmenu. If this problem continuees to exist, please reopen this issue.
