### ISSUE TITLE
Latest version (18-08-2015) has unwanted side effect on notifications

### ISSUE THREAD

**Issue by jandobbelsteen** [cosmocode/edittable#84]
Updating the edittable plugin to the latest version (18-08-2015) in my dokuwiki (both Hrun as Detritus) has the unwanted side effect that notifications become completely filled with icons, like shown below.

![schermafbeelding 2015-08-25 om 16 30 43](https://cloud.githubusercontent.com/assets/6114015/9469450/65c70252-4b47-11e5-8713-4de46ffb61bd.png)

becomes

![schermafbeelding 2015-08-25 om 16 30 00](https://cloud.githubusercontent.com/assets/6114015/9469466/77d76c98-4b47-11e5-8645-0fba0b2a85de.png)

I've verified that switching off the edittable plugin removes this side effect.

**Comment by micgro42** [comment]
@jandobbelsteen can you provide possible error messages from the JavaScript console please?

Could you also provide a list of activated plugins?

**Comment by jandobbelsteen** [comment]
Okay,

No errors or warnings.

The list of activated plugins, including the built-in plugins:
- ACL Manager
- addnewpage
- authplain
- backup
- bookcreator
- cloud
- comment
- config
- csv
- definitionlist
- dw2pdf
- edittable
- extension
- include
- info
- navi
- newpagetemplate
- nspages
- orphanswanted
- pagelist
- pagequery
- popularity
- refnotes
- revert
- safefnrecode
- styling
- tag
- templatepagename
- text
- upgrade
- usermanager

**Comment by jandobbelsteen** [comment]
It seems to be browser related! I'm using Safari as my default browser, but within Firefox everything seems to work fine.

**Comment by splitbrain** [comment]
I saw the problem on a customer's setup using an older Chrome
