### ISSUE TITLE
edittable 2015-08-27 conflicts with other JavaScript under Dokuwiki 2014-09-29d "Hrun"

### ISSUE THREAD

**Issue by konus1** [cosmocode/edittable#85]
I used Dokuwiki Version 2014-09-29d "Hrun". After updating to the last version of edittable 2015-08-27, several other things using JavaScript did not work anymore. Even in the built-in editor all buttons where missing.
In Firefox Console I found the following JavaScript error:

"SyntaxError: invalid increment operand                 js.php:23:614384"

After Updating to the new Version of Dokuwiki 2015-08-10a "Detritus", everything works again. So I guess, the compatibility indicated on the plug-in home page at https://www.dokuwiki.org/plugin:edittable is not correct.

After Updating to Hrun the JavaScript Console shows the following warning:
"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create js.php:24:621768"

I guess, all of this has to do with the jQuery version used.
Thank you for this wonderful software!

**Comment by atisne** [comment]
Same behavior with "Ponder Stibbons".

**Comment by micgro42** [comment]
I'm sorry I am unable to reproduce these issues, both with Hrun and with Ponder Stibbons. It works fine for me. Could this be a caching issue?

And could you verify that this issue still exists with the current edittable version 2015-09-01? (Even so there was no change to the javascript).

**Comment by atisne** [comment]
Thanks for your reply.
I purged both the client and server caches but the issue is still there.
I used the edittable current version -through the plugin manager-.
Immediately (without cleaning any cache) after I uninstall the plugin, the edition toolbar come back.

FYI, my wikis are in farm mode.

**Comment by konus1** [comment]
I can't test it anymore, because I have updated to Hrun. I guess this can be closed.

**Comment by micgro42** [comment]
Hrun had a bug in the javascript compression which introduced an error with the new edittable. That bug was fixed Detritus. The newest edittable version includes a workaround for that bug and should now work under Hrun as intended.

**Comment by atisne** [comment]
Well, the issue remains with Ponder Stibbons.
I know I have to plan an upgrade.
