### ISSUE TITLE
 dTree is not defined, DOKU_BASE is not defined

### ISSUE THREAD

**Issue by Mathilu** [cosmocode/edittable#88]
with edittable activated, Dokuwiki is very slow, it takes about 30 seconds to load a page. I run Dokuwiki on a Raspberry Pi 1 with nginix, usualy page load times are about 1 second. 
Indexmenu is broken, when edittable is activated. 
I get these JS errors:
ReferenceError: dTree is not defined anbieter:telekom:beschwerdemanagement:120:5
ReferenceError: DOKU_BASE is not defined script-cmpr.js:1:5893

With indexmenu disabled, i get the same slow responses, but only this JS error:
ReferenceError: DOKU_BASE is not defined1 script-cmpr.js:1:5893

**Comment by micgro42** [comment]
Please update your DokuWiki installation to Detritus, that should fix it.

**Comment by micgro42** [comment]
Also fixed in the newest edittable version.

**Comment by Mathilu** [comment]
I'm already on the newest DokuWiki Release 2015-08-10a "Detritus". Edittable is also up to date (Version 2015-09-01). 
But edittable and indexmenu aren't working. With edittable active indexmenu is broken and load times are at 30sec.

**Comment by splitbrain** [comment]
I've seen indexmenu and edittable work fine together after the recent upgrades. @Mathilu can you recheck? It might have been a stale cache or an upgrade that didn't run through. Just reinstall indexmenu and edittable. If you're installing manually, make sure to refresh the dokuwiki cache by resaving your configuration.

**Comment by Mathilu** [comment]
I've just tried the following:
1. uninstalled indexmenu
2. activated edittable
3. tried to open my wiki 
-> dokuwik again was very slow and i get the error: ReferenceError: DOKU_BASE is not defined script-cmpr.js:1:7077
4. resaved the configuration
5. loaded my wiki again. slow and the same error again. 

so i think indexmenu isn't the problem. 



- reinstalled indexmenu by using the "reinstall" button in the extension manager
- reinstalled edittable by uninstalling and installing again
- resaved the configuration
but i get the same error again, indexmenu is broken and dokuwiki is unusable slow  :-(
