### ISSUE TITLE
Table in editmode does not fit on page

### ISSUE THREAD

**Issue by konus1** [cosmocode/edittable#89]
If I open a table in edit mode, and there are some columns with more text into it, the table does not fit into the page width. Instead of this, the right columns disappear. 
If I drag the columns smaller, than word-wrap is applied to the columns with more text and it is possible to adjust the table to fit into page width.

I would prefer, that the table opens with word wrap and tries to auto-adjust the columns size to fit into the page. I think, this was also the normal behavior before the last update.

![screenshot](https://cloud.githubusercontent.com/assets/2836147/9629914/a8179240-5176-11e5-93e5-30d90a18a233.jpg)

**Comment by konus1** [comment]
Even worse: after adding a row in the table, everything is like before.

**Comment by konus1** [comment]
Problem still exists in Version 2015-09-01.

**Comment by micgro42** [comment]
It seems the calculation of column-widths could use some general improvement. I will look into it when I can find the time, but it might take a while.

**Comment by konus1** [comment]
@micgro42 Is there anything I can help you with to improve progress?

**Comment by konus1** [comment]
I would be really happy If you would find some time to look into this in the near future. :-)

**Comment by micgro42** [comment]
Hey the problem appears to be with the plugin AutoColumnSize for handsontable https://github.com/handsontable/handsontable/tree/master/src/plugins/autoColumnSize
* One option I see is to deactivate the plugin on a per-page basis or for the entire wiki via an config option and to provide a fixed width per column. (This has yet to be implemented).
* Another Option might be for you to go back to a version of this plugin before we updated handsontable: https://github.com/cosmocode/edittable/releases/tag/2015-06-17
* The third Option would be to actually work out what the incompatibility between the plugin and Dokuwiki is and fix it. However this may require quite some uninterrupted time to work on the problem and I don't see this coming yet.

Pull requests for this issue would be very welcomed.

**Comment by konus1** [comment]
Thank you for the answer and thank you for the link to the previous version! I installed it and now I can work again. Great!
Unfortunately I am technically not able to solve the issue by myself and do a pull request. 

If you think, the problem is related to autoCoumnSize, maybe it would be better to report the problem over there? I did not find a related bug report. 

I just don't know how to test it and make a reproducible bug report. Do you have an idea how to accomplish this?

**Comment by jazzl0ver** [comment]
Hi. There's a 0.25.1 version of handsontable, which probably has this issue fixed. Can you please release edittable with the new handontable version?

**Comment by micgro42** [comment]
Hey @konus1 ,
I updated edittable with and it should have improved some editor issues. Could you check if the problems persist?

@jazzl0ver I'd like to update to the newest version of handsontable. However that would mean some more days of work which I do not have available right now.
