### ISSUE TITLE
JavaScript syntax error when edittable is enabled

### ISSUE THREAD

**Issue by real-or-random** [cosmocode/edittable#90]
I get "SyntaxError: invalid increment operand js.php:23:614722"
The problem is the javascript compression:

The source file contains 
```
function newUniqueString(){return'__$'+Math.floor(Math.random()*1e9)+'$'+++counter+'$__';}
```
but it should contain
```
function newUniqueString(){return'__$'+Math.floor(Math.random()*1e9)+'$'+ ++counter+'$__';}
```
```+++``` is not parseable.

This is probably the cause for https://github.com/cosmocode/tagging/issues/22

Note: This is with the newest version of edittable but on Hrun... I could not test it with the current DokuWiki version yet.

**Comment by micgro42** [comment]
Yes, you are right, there was a bug in the javascript compression in Hrun, but it has been fixed in Detritus. 
However that may explain lots of the bugs we have seen after this edittable update. I'll check if I can implement workarounds for Hrun.

**Comment by micgro42** [comment]
The workaround was simple, so the newest version of edittable should now work with Hrun.
