### ISSUE TITLE
Interference with default stylesheet for messages

### ISSUE THREAD

**Issue by vogtadi** [cosmocode/edittable#91]
The Edittable Plugin interferes with the style definitions for dokuwiki messages (div.notify etc). The effect is, that these messages get incorrectly rendered (the icon, which is a background image, gets repeated all over the message and the border is not what it should be)

The root cause seems to be an extra "@charset "UTF-8";" in handsometable.full.less around line 1234, which gets copied into the production stylesheet delivered to the client and due to its erroneous placement disables a css rule.

**Comment by splitbrain** [comment]
I reported this as an upstream bug: https://github.com/handsontable/handsontable/issues/2843

**Comment by vogtadi** [comment]
Not sure whether that is place where the error took place. I downloaded "handsontable" 0.16.1 and it does NOT look like the problem is there. I rather suspect, that something in the "build" process to get the handsontable (.css) file included in the edittable plugin (as a .less) file is incorrect. there seems to be a dependency (pickaday), which contains that @charset instruction (correctly) at the beginning of the file. This seem be be just catenated as is into the handsontable.less of the edititable plugin.

**Comment by vogtadi** [comment]
Still an issue in the latest release of the plugin. It looks like this is also the reason, why the dokuwiki homepage itself has some layout problems (e.g. on https://www.dokuwiki.org/plugin:math).
I am still under the impression, that the **build process of edittable** needs to be fixed.

**Comment by vogtadi** [comment]
Thanks!

**Comment by stvoigt** [comment]
Ich kehre zurück am 18.04.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten. Herzlichen Dank
für ihr Verständnis.

I will answer your message after returning.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[cosmocode/edittable] Interference with default stylesheet for messages
(#91)" gesendet am 13.04.2017 09:32:48.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
