### ISSUE TITLE
edittable plugin causes problems with page editing

### ISSUE THREAD

**Issue by jjkavalam** [cosmocode/edittable#92]
I installed the edittable (https://www.dokuwiki.org/plugin:edittable) plugin on my dokuwiki today (October 1, 2015) by searching for "edittable" in the extension manager screen of Admin user.

When the plugin is enabled, I am unable to access the formatting buttons in the embedded editor.
(Please see the screenshots)

![my dokuwiki version](https://cloud.githubusercontent.com/assets/4114293/10212783/ba1275c4-6836-11e5-9519-c58568260d83.PNG)

![with edittable plugin disabled](https://cloud.githubusercontent.com/assets/4114293/10212785/c462081e-6836-11e5-9084-2da90ac7f25b.PNG)

![edittable plugin is now enabled](https://cloud.githubusercontent.com/assets/4114293/10212793/eb98249a-6836-11e5-9565-bf3a7301df77.PNG)

![with edittable plugin enabled](https://cloud.githubusercontent.com/assets/4114293/10212794/f32c6f2c-6836-11e5-9fcc-5fb4a9accb54.PNG)

**Comment by sganarel** [comment]
I have the same issue.

Could you fix it please ?

**Comment by micgro42** [comment]
That is an javascript issue. Could you provide possible error messages from the JavaScript console please?

**Comment by jjkavalam** [comment]
Thank you for the response.

As requested, I have checked the JavaScript console and found the following error message only when the plugin is enabled.

[Mozilla FireFox ESR 38.3.0] SyntaxError: invalid increment operand [js.php:23:613534]

[Google Chrome 45.0.2454.101 m] Uncaught ReferenceError: Invalid left-hand side expression in postfix operation [js.php:23]

**Comment by micgro42** [comment]
Please upgrade your dokuwiki to the current release 2015-08-10a Detritus. Hrun had a bug in javascript compression.

**Comment by micgro42** [comment]
Since there have been no more answers, I assume that this has been fixed by upgrading dokuwiki. Feel free to reopen/comment on this issue if the problem actually persists.

**Comment by jjkavalam** [comment]
Thank you very much for the solution. Upgrading to 2015-08-10a Detritus indeed fixes the problem.

I apologize for the late reply.
