### ISSUE TITLE
edittable and tagging don't work together

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [cosmocode/edittable#93]
When activating the edittable plugin the tagging plugin doesn't work correctly any more.

Regards
Juergen

**Comment by micgro42** [comment]
Could you be more detailed about what  "doesn't work correctly any more" means? What version of Dokuwiki and what browser are you using?

**Comment by Juergen-aus-Koeln** [comment]
After installing the latest versions of both plugins it works.

Regards
Juergen

**Comment by micgro42** [comment]
ok
