### ISSUE TITLE
New version of edittable kills Edit Toolbar and re-sizing arrows (Ponder Stibbons)

### ISSUE THREAD

**Issue by paulhuysing** [cosmocode/edittable#95]
After installing the latest version of Edittable I noticed it killed the Edit Toolbar and Re-sizing arrows in edit window.  (Ponder Stibbons)

**Comment by micgro42** [comment]
Yes, edittable is most likely not compatible with Ponder Stibbons anymore. Please update to the current stable version of Dokuwiki: Detritus 2015-08-10a
