### ISSUE TITLE
EditTable doesn't work on IE8

### ISSUE THREAD

**Issue by nelidimitrova** [cosmocode/edittable#97]
Hello.
I have a problem with the plugin. I use Dokuwiki 2015-08-10a "Detritus". I have a couple of installed plugins: anchor, npd (New Page Dialog), dw2pdf, editX, note, nspages, uncmap, wrap.
I installed EditTable. Everything works fine on Mozilla Firefox 42.0 and on other versions of Firefox.
BUT
it doesn't work on IE 8. I received these JS errors when debugging:
  Expected identifier, string or number  js.php?t=dokuwiki&tseed=a1824138eb599df50aeb47bdc06d841d, line 35420 character 258
  Object expected  button.js, line 7 character 1
  Expected identifier, string or number  js.php?t=dokuwiki&tseed=a1824138eb599df50aeb47bdc06d841d, line 35420 character 258
  Object expected  button.js, line 7 character 1
  Expected identifier, string or number  js.php?t=dokuwiki&tseed=a1824138eb599df50aeb47bdc06d841d, line 35420 character 258
  Object expected  button.js, line 7 character 1
  Expected identifier, string or number  js.php?t=dokuwiki&tseed=d1b61eab3bd21c32e2d8b96d6e81ad06, line 24 character 123446
  Object expected  button.js, line 7 character 1
button.js is part of npd plugin and on line 7 there is -> jQuery(function(){
My "create new page" button (npd plugin) is missing and the toolbar in edit mode is missing too. If I disable EditTable plugin everything is working again.
I tried some things that I read in other issue (#69) but they didn't helped. And also changing "compress" option is not acceptable in my case because we use 3-4 web apps that doesn't work when I disable compress.
I will be very happy if you can help me with this problem. My users use IE8 and for many reasons they can not replace it with Firefox.
Thanks in advanced.

**Comment by micgro42** [comment]
Yes, the current version does not work on IE8 anymore and this cannot be fixed, because the error lies within the used 3rd-Party library handsontable. However I have tagged the last version before we upgraded the plugin to a new version of handsontable and maybe you can try to use this one: 

https://github.com/cosmocode/edittable/releases/tag/2015-06-17

**Comment by nelidimitrova** [comment]
Thank you for your time. I will try this version as soon as I can.

**Comment by nelidimitrova** [comment]
I finally had a chance to test this version and it works perfectly with IE8. Many many thanks. (bow)
